//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuGoiMon
    {
        public int MaPhieu { get; set; }
        public string MaMon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<bool> GhiChu { get; set; }
    
        public virtual PhieuGoiMon PhieuGoiMon { get; set; }
        public virtual ThucDon ThucDon { get; set; }
    }
}
