//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using QuanLyCaPhe.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon:BaseViewModel
    {
        private string _maHoaDon;
        private string _maMon;
        private Nullable<int> _soLuong;
        private string _ghiChu;
        private Nullable<decimal> _tongCong;
       

        public string MaHoaDon
        {
            get
            {
                return _maHoaDon;
            }
            set
            {
                if (_maHoaDon != value)
                {
                    _maHoaDon = value;
                    RaisePropertyChanged("MaHoaDon");
                }
            }
        }
        public string MaMon
        {
            get
            {
                return _maMon;
            }
            set
            {
                if (_maMon != value)
                {
                    _maMon = value;
                    RaisePropertyChanged("MaMon");
                }
            }
        }
        public Nullable<int> SoLuong
        {
            get
            {
                return _soLuong;
            }
            set
            {
                if (_soLuong != value)
                {
                    _soLuong = value;
                    RaisePropertyChanged("SoLuong");
                }
            }
        }
        public string GhiChu
        {
            get
            {
                return _ghiChu;
            }
            set
            {
                if (_ghiChu != value)
                {
                    _ghiChu = value;
                    RaisePropertyChanged("GhiChu");
                }
            }
        }
        public Nullable<decimal> TongCong
        {
            get
            {
                return _tongCong;
            }
            set
            {
                if (_tongCong != value)
                {
                    _tongCong = value;
                    RaisePropertyChanged("TongCong");
                }
            }
        }

        public virtual HoaDon HoaDon { get; set; }
        public virtual ThucDon ThucDon { get; set; }
    }
}
