//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using QuanLyCaPhe.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class DonViTinh:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViTinh()
        {
            this.ThucDons = new HashSet<ThucDon>();
        }
        private string _maDonViTinh;
        private string _tenDonViTinh;
        private string _ghiChu;
        public string MaDonViTinh
        {
            get
            {
                return _maDonViTinh;
            }
            set
            {
                if(_maDonViTinh!=value)
                {
                    _maDonViTinh = value;
                    RaisePropertyChanged("MaDonViTinh");
                }
            }
        }
       
        
        public string TenDonViTinh
        {
            get
            {
                return _tenDonViTinh;
            }
            set
            {
                if (_tenDonViTinh != value)
                {
                    _tenDonViTinh = value;
                    RaisePropertyChanged("TenDonViTinh");
                }
            }
        }

        public string GhiChu
        {
            get
            {
                return _ghiChu;
            }
            set
            {
                if (_ghiChu != value)
                {
                    _ghiChu = value;
                    RaisePropertyChanged("GhiChu");
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThucDon> ThucDons { get; set; }
    }
}
