//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanHeNguoiDung_QuyenHan
    {
        public string MaQuanHe { get; set; }
        public Nullable<bool> DinhChi { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MaQuyenHan { get; set; }
    
        public virtual QuyenHan QuyenHan { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
