//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using QuanLyCaPhe.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKhachHang:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiKhachHang()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        private string _maLoaiKhachHang;
        private string _tenLoaiKhachHang;
        private string _ghiChu;
        public string MaLoaiKhachHang
        {
            get
            {
                return _maLoaiKhachHang;
            }
            set
            {
                if (_maLoaiKhachHang != value)
                {
                    _maLoaiKhachHang = value;
                    RaisePropertyChanged("MaLoaiKhachHang");
                }
            }
        }

        public string TenLoaiKhachHang
        {
            get
            {
                return _tenLoaiKhachHang;
            }
            set
            {
                if (_tenLoaiKhachHang != value)
                {
                    _tenLoaiKhachHang = value;
                    RaisePropertyChanged("TenLoaiKhachHang");
                }
            }
        }


        public string GhiChu
        {
            get
            {
                return _ghiChu;
            }
            set
            {
                if (_ghiChu != value)
                {
                    _ghiChu = value;
                    RaisePropertyChanged("GhiChu");
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
