//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using QuanLyCaPhe.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class KhachHang : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }

        private int _maKhachHang;
        private string _tenKhachHang;
        private string _diaChi;
        private string _gioiTinh;
        private string _dienThoaiDiDong;
        private string _maLoaiKhachHang;
        private bool _daXoa;
        private LoaiKhachHang _loaiKhachHang;
        public int MaKhachHang
        {
            get
            {
                return _maKhachHang;
            }
            set
            {
                if (_maKhachHang != value)
                {
                    _maKhachHang = value;
                    RaisePropertyChanged("MaKhachHang");
                }
            }
        }
        public string TenKhachHang
        {
            get
            {
                return _tenKhachHang;
            }
            set
            {
                if (_tenKhachHang != value)
                {
                    _tenKhachHang = value;
                    RaisePropertyChanged("TenKhachHang");
                }
            }
        }
        public string DiaChi
        {
            get
            {
                return _diaChi;
            }
            set
            {
                if (_diaChi != value)
                {
                    _diaChi = value;
                    RaisePropertyChanged("DiaChi");
                }
            }
        }
        public string GioiTinh
        {
            get
            {
                return _gioiTinh;
            }
            set
            {
                if (_gioiTinh != value)
                {
                    _gioiTinh = value;
                    RaisePropertyChanged("GioiTinh");
                }
            }
        }
        public string DienThoaiDiDong
        {
            get
            {
                return _dienThoaiDiDong;
            }
            set
            {
                if (_dienThoaiDiDong != value)
                {
                    _dienThoaiDiDong = value;
                    RaisePropertyChanged("DienThoaiDiDong");
                }
            }
        }
        public string MaLoaiKhachHang
        {
            get
            {
                return _maLoaiKhachHang;
            }
            set
            {
                if (_maLoaiKhachHang != value)
                {
                    _maLoaiKhachHang = value;
                    RaisePropertyChanged("MaLoaiKhachHang");
                }
            }
        }

        public bool DaXoa
        {
            get
            {
                return _daXoa;
            }
            set
            {
                if (_daXoa != value)
                {
                    _daXoa = value;
                    RaisePropertyChanged("DaXoa");
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual LoaiKhachHang LoaiKhachHang
        {
            get
            {
                return _loaiKhachHang;
            }
            set
            {
                if (_loaiKhachHang != value)
                {
                    _loaiKhachHang = value;
                    RaisePropertyChanged("LoaiKhachHang");
                }
            }
        }
    }
}
