//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using QuanLyCaPhe.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }

        private string _maNhanVien;
        private string _tenNhanVien;
        private string _gioiTinh;
        private string _diaChi;
        private string _cmnd;
        private Nullable<System.DateTime> _ngayCap;
        private Nullable<System.DateTime> _ngaySinh;
        private string _noiCapCMND;
        private string _dienThoaiDiDong;
        private string _trangThaiLamViec;

        public string MaNhanVien
        {
            get
            {
                return _maNhanVien;
            }
            set
            {
                if (_maNhanVien != value)
                {
                    _maNhanVien = value;
                    RaisePropertyChanged("MaNhanVien");
                }
            }
        }
        public string TenNhanVien
        {
            get
            {
                return _tenNhanVien;
            }
            set
            {
                if (_tenNhanVien != value)
                {
                    _tenNhanVien = value;
                    RaisePropertyChanged("TenNhanVien");
                }
            }
        }
        public string GioiTinh
        {
            get
            {
                return _gioiTinh;
            }
            set
            {
                if (_gioiTinh != value)
                {
                    _gioiTinh = value;
                    RaisePropertyChanged("GioiTinh");
                }
            }
        }
        public string DiaChi
        {
            get
            {
                return _diaChi;
            }
            set
            {
                if (_diaChi != value)
                {
                    _diaChi = value;
                    RaisePropertyChanged("DiaChi");
                }
            }
        }
        public string CMND
        {
            get
            {
                return _cmnd;
            }
            set
            {
                if (_cmnd != value)
                {
                    _cmnd = value;
                    RaisePropertyChanged("CMND");
                }
            }
        }
        public Nullable<System.DateTime> NgayCap
        {
            get
            {
                return _ngayCap;
            }
            set
            {
                if (_ngayCap != value)
                {
                    _ngayCap = value;
                    RaisePropertyChanged("NgayCap");
                }
            }
        }
        public string NoiCapCMND
        {
            get
            {
                return _noiCapCMND;
            }
            set
            {
                if (_noiCapCMND != value)
                {
                    _noiCapCMND = value;
                    RaisePropertyChanged("NoiCapCMND");
                }
            }
        }
        public Nullable<System.DateTime> NgaySinh
        {
            get
            {
                return _ngaySinh;
            }
            set
            {
                if (_ngaySinh != value)
                {
                    _ngaySinh = value;
                    RaisePropertyChanged("NgaySinh");
                }
            }
        }
        public string DienThoaiDiDong
        {
            get
            {
                return _dienThoaiDiDong;
            }
            set
            {
                if (_dienThoaiDiDong != value)
                {
                    _dienThoaiDiDong = value;
                    RaisePropertyChanged("DienThoaiDiDong");
                }
            }
        }
        public string TrangThaiLamViec
        {
            get
            {
                return _trangThaiLamViec;
            }
            set
            {
                if (_trangThaiLamViec != value)
                {
                    _trangThaiLamViec = value;
                    RaisePropertyChanged("TrangThaiLamViec");
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
