//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyDangNhap
    {
        public int MaNhatKy { get; set; }
        public System.DateTime NgayDangNhap { get; set; }
        public System.DateTime NgayDangXuat { get; set; }
        public string TenTaiKhoan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
