//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Model
{
    using QuanLyCaPhe.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.NhatKyDangNhaps = new HashSet<NhatKyDangNhap>();
            this.QuanHeNguoiDung_QuyenHan = new HashSet<QuanHeNguoiDung_QuyenHan>();
        }

        private string _tenTaiKhoan;
        private string _matKhau;
        private string _maNhanVien;
        private string _qrCode;

    
        public string TenTaiKhoan
        {
            get
            {
                return _tenTaiKhoan;
            }
            set
            {
                if (_tenTaiKhoan != value)
                {
                    _tenTaiKhoan = value;
                    RaisePropertyChanged("TenTaiKhoan");
                }
            }
        }
        public string MatKhau
        {
            get
            {
                return _matKhau;
            }
            set
            {
                if (_matKhau != value)
                {
                    _matKhau = value;
                    RaisePropertyChanged("MatKhau");
                }
            }
        }
        public string MaNhanVien
        {
            get
            {
                return _maNhanVien;
            }
            set
            {
                if (_maNhanVien != value)
                {
                    _maNhanVien = value;
                    RaisePropertyChanged("MaNhanVien");
                }
            }
        }
        public string QRCode
        {
            get
            {
                return _qrCode;
            }
            set
            {
                if (_qrCode != value)
                {
                    _qrCode = value;
                    RaisePropertyChanged("QRCode");
                }
            }
        }

        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhatKyDangNhap> NhatKyDangNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanHeNguoiDung_QuyenHan> QuanHeNguoiDung_QuyenHan { get; set; }
    }
}
